AWSTemplateFormatVersion: 2010-09-09
Description: Configure a hosted zone and a DNS record in Route 53

Parameters:
  MasterStackName:
    Type: String
  VpcId:
    Type: String
    Default: ""
  ExistingHostedZoneId:
    Type: String
    Default: ""
  RecordExist:
    Type: String
    Default: ""
  DomainName:
    Type: String
    Default: ""
  RecordName:
    Type: String
    Default: ""
  LoadBalancerDNSName:
    Type: String
    Default: ""


Conditions:
  CreateHostedZone:
    !Equals [ !Ref ExistingHostedZoneId, ""]
  CreateRecord:
    !Equals [ !Ref RecordExist, "false"]

Resources:
  HostedZone:
    Type: AWS::Route53::HostedZone
    Condition: CreateHostedZone
    Properties:
      Name:
        !Ref DomainName
      HostedZoneConfig:
        Comment: "A2C created hosted zone"
      VPCs:
        - VPCId:
            !Ref VpcId
          VPCRegion:
            Ref: 'AWS::Region'
  DnsRecord:
    Type: AWS::Route53::RecordSet
    Condition: CreateRecord
    Properties:
      HostedZoneId:
        !If
        - CreateHostedZone
        - !Ref HostedZone
        - !Ref ExistingHostedZoneId
      Name: !Join [ '', [ !Ref 'RecordName', ., !Ref 'DomainName' ] ]
      Type: CNAME
      TTL: '900'
      ResourceRecords:
        - !Ref LoadBalancerDNSName

Outputs:
  HostedZoneId:
    Value:
      !If
      - CreateHostedZone
      - !Ref HostedZone
      - !Ref ExistingHostedZoneId
    Export:
      Name: !Sub '${MasterStackName}-HostedZoneId'